spring:
  application:
    name: zipkin-server
server:
  port: 9014
management:
  metrics:
    web:
      server:
        auto-time-requests: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9011/eureka/